config/routes.rb
Beertradr::Application.routes.draw do
  resources :brews

  resources :brewers

  root :to => 'brewers#index'

end

app/models/brew.rb
class Brew < ActiveRecord::Base
  attr_accessible :brewer_id, :description, :name, :abv, :ibu
  belongs_to :brewer
end

app/models/brewer.rb
class Brewer < ActiveRecord::Base
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name, :zip
  has_many :brews

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= Brewer.find(session[:brewer_id]) if session[:brewer_id]
  end
  helper_method :current_user
end

app/controllers/brewers_controller.rb
class BrewersController < ApplicationController
  # GET /brewers
  # GET /brewers.json
  def index
    @brewers = Brewer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brewers }
    end
  end

  # GET /brewers/1
  # GET /brewers/1.json
  def show
    @brewer = Brewer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brewer }
    end
  end

  # GET /brewers/new
  # GET /brewers/new.json
  def new
    @brewer = Brewer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brewer }
    end
  end

  # GET /brewers/1/edit
  def edit
    @brewer = Brewer.find(params[:id])
  end

  # POST /brewers
  # POST /brewers.json
  def create
    @brewer = Brewer.new(params[:brewer])

    respond_to do |format|
      if @brewer.save
        session[:brewer_id] = @brewer.id
        format.html { redirect_to @brewer, notice: 'Brewer was successfully created.' }
        format.json { render json: @brewer, status: :created, location: @brewer }
      else
        format.html { render action: "new" }
        format.json { render json: @brewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brewers/1
  # PUT /brewers/1.json
  def update
    @brewer = Brewer.find(params[:id])

    respond_to do |format|
      if @brewer.update_attributes(params[:brewer])
        format.html { redirect_to @brewer, notice: 'Brewer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brewers/1
  # DELETE /brewers/1.json
  def destroy
    @brewer = Brewer.find(params[:id])
    @brewer.destroy

    respond_to do |format|
      format.html { redirect_to brewers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/brews_controller.rb
class BrewsController < ApplicationController
  # GET /brews
  # GET /brews.json
  def index
    @brews = Brew.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brews }
    end
  end

  # GET /brews/1
  # GET /brews/1.json
  def show
    @brew = Brew.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brew }
    end
  end

  # GET /brews/new
  # GET /brews/new.json
  def new
    @brew = Brew.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brew }
    end
  end

  # GET /brews/1/edit
  def edit
    @brew = Brew.find(params[:id])
  end

  # POST /brews
  # POST /brews.json
  def create
    @brew = Brew.new(params[:brew])

    respond_to do |format|
      if @brew.save
        format.html { redirect_to @brew, notice: 'Brew was successfully created.' }
        format.json { render json: @brew, status: :created, location: @brew }
      else
        format.html { render action: "new" }
        format.json { render json: @brew.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brews/1
  # PUT /brews/1.json
  def update
    @brew = Brew.find(params[:id])

    respond_to do |format|
      if @brew.update_attributes(params[:brew])
        format.html { redirect_to @brew, notice: 'Brew was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brew.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brews/1
  # DELETE /brews/1.json
  def destroy
    @brew = Brew.find(params[:id])
    @brew.destroy

    respond_to do |format|
      format.html { redirect_to brews_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
def create
  brewer = Brewer.find_by_email(params[:email])
  if brewer && brewer.authenticate(params[:password])
    session[:brewer_id] = brewer.id
    redirect_to root_url, :notice => "Logged in!"
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

def destroy
  session[:brewer_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brewers_helper.rb
module BrewersHelper
end

app/helpers/brews_helper.rb
module BrewsHelper
end

app/views/brewers/_form.html.erb
<%= form_for(@brewer) do |f| %>
  <% if @brewer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewer.errors.count, "error") %> prohibited this brewer from being saved:</h2>

      <ul>
      <% @brewer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :zip %><br />
    <%= f.number_field :zip, :class => 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit :class =>  'btn btn-default'%>
  </div>
<% end %>

app/views/brewers/edit.html.erb
<h1>Editing brewer</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewer %> |
<%= link_to 'Back', brewers_path %>

app/views/brewers/index.html.erb
<h1>Listing brewers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Zip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @brewers.each do |brewer| %>
  <tr>
    <td><%= brewer.name %></td>
    <td><%= brewer.zip %></td>
    <td><%= link_to 'Show', brewer %></td>
    <td><%= link_to 'Edit', edit_brewer_path(brewer) %></td>
    <td><%= link_to 'Destroy', brewer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Brewer', new_brewer_path %>

app/views/brewers/new.html.erb
<h1>New brewer</h1>

<%= render 'form' %>

<%= link_to 'Back', brewers_path %>

app/views/brewers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @brewer.name %>
</p>

<p>
  <b>Zip:</b>
  <%= @brewer.zip %>
</p>


<%= link_to 'Edit', edit_brewer_path(@brewer) %> |
<%= link_to 'Back', brewers_path %>

app/views/brews/_form.html.erb
<%= form_for(@brew) do |f| %>
  <% if @brew.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brew.errors.count, "error") %> prohibited this brew from being saved:</h2>

      <ul>
      <% @brew.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :ibu %><br />
    <%= f.text_field :ibu %>
  </div>
  <div class="field">
    <%= f.label :abv %><br />
    <%= f.text_field :abv %>
  </div>
  <div class="field">
    <%= f.label :brewer_id %><br />
    <%= f.hidden_field :brewer_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brews/edit.html.erb
<h1>Editing brew</h1>

<%= render 'form' %>

<%= link_to 'Show', @brew %> |
<%= link_to 'Back', brews_path %>

app/views/brews/index.html.erb
<h1>Listing brews</h1>

<div id="map"></div>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Brewer</th>
    <th>Zip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @brews.each do |brew| %>
  <tr>
    <td><%= brew.name %></td>
    <td><%= brew.description %></td>
    <td><%= brew.brewer_id %></td>
    <td><%= brew.brewer.zip %></td>
    <td><%= link_to 'Show', brew %></td>
    <td><%= link_to 'Edit', edit_brew_path(brew) %></td>
    <td><%= link_to 'Destroy', brew, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Brew', new_brew_path %>

<script>
$(function(){

  function convert(tsv){

    var lines=tsv.split("\n");

    var result = [];

    var headers=lines[0].split("\t");

    for(var i=1;i<lines.length-1;i++){

      var obj = {};
      var currentline=lines[i].split("\t");

      for(var j=0;j<headers.length;j++){
        obj[headers[j]] = currentline[j];
      }

      result.push(obj);

    }

    return result;
  }

  function getLocation()
    {
    if (navigator.geolocation)
      {
      navigator.geolocation.getCurrentPosition(showPosition);
      }
    else{x.innerHTML="Geolocation is not supported by this browser.";}
    }
  function showPosition(position)
    {
    x.innerHTML="Latitude: " + position.coords.latitude +
    "<br>Longitude: " + position.coords.longitude;
    }


  var map = L.map('map').setView([40.009594, -105.253912], 13);

  L.tileLayer('http://{s}.tile.cloudmade.com/8ee2a50541944fb9bcedded5165f09d9/997/256/{z}/{x}/{y}.png', {
      attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://cloudmade.com">CloudMade</a>',
      maxZoom: 18
  }).addTo(map);

  var marker = L.marker([51.5, -0.09]).addTo(map);

  var zips = <%= @brews.map{ |brew| brew.brewer.zip } %>;

  $.each(zips, function(key, value){
    var marker = L.marker([51.5, -0.09]).addTo(map).bindPopup('A pretty CSS3 popup. <br> Easily customizable.');
  });

  <%= @brew.each do |brew| %>
    var marker = L.marker([<%= brew.lat %>, <%= brew.long %>]).addTo(map).bindPopup("#{brew.description}");
  <% end %>

});

</script>

app/views/brews/new.html.erb
<h1>New brew</h1>

<%= render 'form' %>

<%= link_to 'Back', brews_path %>

app/views/brews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @brew.name %>
</p>

<p>
  <b>Description:</b>
  <%= @brew.description %>
</p>

<p>
  <b>Brewer:</b>
  <%= Brewer.find(@brew.brewer_id).name %>
</p>

<p>
  <b>IBU:</b>
  <%= @brew.ibu %>
</p>

<p>
  <b>ABV:</b>
  <%= @brew.abv %>
</p>

<%= link_to 'Edit', edit_brew_path(@brew) %> |
<%= link_to 'Back', brews_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beertradr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css" />
</head>
<body>
	<div class="container">
		<nav class="navbar navbar-default" role="navigation">
		  <!-- Brand and toggle get grouped for better mobile display -->
		  <div class="navbar-header">
		    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		      <span class="sr-only">Toggle navigation</span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		      <span class="icon-bar"></span>
		    </button>
		    <a class="navbar-brand" href="#">Beer Trad<span class="pink">r</span></a>
		  </div>

		  <!-- Collect the nav links, forms, and other content for toggling -->
		  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		    <ul class="nav navbar-nav">
		      <li class="active"><a href="#">Add Your Beer <i class="glyphicon glyphicon-plus"></i></a></li>
		      <li><a href="#">Trade</a></li>
		    </ul>
		    <ul class="nav navbar-nav navbar-right">
		      <li><a href="#">Logout</a></li>
		    </ul>
		  </div><!-- /.navbar-collapse -->
		</nav>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <header>

  </header>
<%= yield %>

	</div>

</body>
</html>